# Generated by Django 2.2.1 on 2019-05-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('total_car_lots', models.PositiveSmallIntegerField(null=True)),
                ('status', models.CharField(choices=[('Temporarily Closed', 'Temporarily Closed'), ('Open', 'Open')], default='Open', max_length=18)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='parking.Company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='CarLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('order_number', models.PositiveSmallIntegerField(null=True)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_lot', to='parking.Parking', verbose_name='Parking')),
            ],
        ),
    ]
