# Generated by Django 2.0 on 2018-02-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default='22-02-2018')),
                ('finish_date', models.DateField()),
                ('parking_space_number', models.CharField(max_length=4)),
                ('phone_number', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=35)),
                ('surname', models.CharField(max_length=35)),
            ],
        ),
    ]
