# Generated by Django 2.2.1 on 2019-05-19 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0001_initial'),
        ('reservation', '0002_auto_20180223_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='parking_space_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='surname',
        ),
        migrations.AddField(
            model_name='reservation',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='car_lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_lot', to='parking.CarLot', verbose_name='CarLot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='regime',
            field=models.IntegerField(choices=[(2, 'Normal (2h)'), (1, 'Fast-Charge (1h)')], default=2),
        ),
        migrations.AddField(
            model_name='reservation',
            name='repeat',
            field=models.IntegerField(choices=[(0, 'Once'), (1, 'Daily'), (2, 'Weekly'), (3, 'Monthly')], default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='repeat_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
