# Generated by Django 2.2.1 on 2019-05-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20190519_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='plate_number',
            field=models.CharField(default='AA111ETE', max_length=8),
            preserve_default=False,
        ),
    ]
