# Generated by Django 2.2.1 on 2019-05-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_plate_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='plate_number',
        ),
    ]
