# Generated by Django 2.2.1 on 2019-05-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_remove_reservation_plate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='plate_number',
            field=models.CharField(default='', max_length=8),
        ),
    ]
