# Generated by Django 2.2.1 on 2019-05-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_reservation_plate_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='repeat_end',
        ),
        migrations.AddField(
            model_name='reservation',
            name='repeat_for',
            field=models.IntegerField(default=1),
        ),
    ]
