# Generated by Django 2.2.1 on 2019-05-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20190522_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='repeat_for',
        ),
        migrations.AddField(
            model_name='reservation',
            name='repeat_end',
            field=models.DateTimeField(null=True),
        ),
    ]
